name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: decode .env from github secrets
      run: |
        echo $FAKERESTAPI_BASE_URL | base64 --decode > .env
      env:
        FAKERESTAPI_BASE_URL: ${{ secrets.FAKERESTAPI_BASE_URL }}
    - run: cat .env
    # - run: npm install
    # - run: npm run test-api
    # - uses: actions/upload-artifact@v2
    #   name: Archive Results
    #   with:
    #     name: Reporting
    #     path: reports