name: Automation Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FAKERESTAPI_BASE_URL: ${{ secrets.FAKERESTAPI_BASE_URL }}
  REQRES_BASE_URL: ${{ secrets.REQRES_BASE_URL }}
  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/my-action
      run: npm run test-api