name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FAKERESTAPI_BASE_URL: ${{ secrets.FAKERESTAPI_BASE_URL }}
  REQRES_BASE_URL: ${{ secrets.REQRES_BASE_URL }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
    - run: npm install
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: test
  #   - run: npm run test-api