name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FAKERESTAPI_BASE_URL: ${{ secrets.FAKERESTAPI_BASE_URL }}
  REQRES_BASE_URL: ${{ secrets.REQRES_BASE_URL }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.2]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: npm run test-api
      name: Archive Results
      with:
        name: Reporting
        path: reports