name: Automation Testing

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron:  '00 00 * * 1-5'

env:
  FAKERESTAPI_BASE_URL: ${{ secrets.FAKERESTAPI_BASE_URL }}
  REQRES_BASE_URL: ${{ secrets.REQRES_BASE_URL }}
  COBAPI_URL: ${{ secrets.COBAPI_URL }}
  
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: damarresin/kiwi:2022-09-26_0912
    steps:
    - uses: actions/checkout@v2
    - name: Preparation Test
      run: |
            mv ./api /app/
            mv ./data /app/
            mv ./helpers /app/
            mv ./tests /app/
            mv package.json /app/
    - name: Run Test
      run: |
            cd /app/
            npm run test-api
    - name: Get Current Time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HH.MM
        utcOffset: "+07:00"
    - name: Use Current Time
      env:
        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
      run: echo Reports $F_TIME
    - name: Reporting
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Reports ${{ steps.current-time.outputs.formattedTime }}
        path: /app/reports
