name: Automation Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FAKERESTAPI_BASE_URL: ${{ secrets.FAKERESTAPI_BASE_URL }}
  REQRES_BASE_URL: ${{ secrets.REQRES_BASE_URL }}
  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/lock.json') }}
    - name: Installing
      run: npm install
    - name: Running Test
      run: npm run test-api
    - name: Reporting
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Reports
        path: reports
