name: Automation Testing

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron:  '00 00 * * 1-5'

env:
  FAKERESTAPI_BASE_URL: ${{ secrets.FAKERESTAPI_BASE_URL }}
  REQRES_BASE_URL: ${{ secrets.REQRES_BASE_URL }}
  COBAPI_URL: ${{ secrets.COBAPI_URL }}
  
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: damarresin/kiwi:2022-09-21_1659
    steps:
    - uses: actions/checkout@v2
#     - name: Run the build process with Docker
#       uses: addnab/docker-run-action@v3
#       with:
#         image: damarresin/kiwi:2022-09-21_1659
#     - uses: actions/checkout@v2
#     - name: npm cache
#       uses: actions/cache@v2
#       with:
#         path: '**/node_modules'
#         key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
#     - name: Installing
#       run: yarn install
    - name: Test
      run: |
          ls -a
          pwd
    - name: Test2
      run: mocha ./tests
#           sudo cp -r . /app/
#           ls -a
#           pwd
#           npm run test-api
#     - name: Get current time
#       uses: josStorer/get-current-time@v2
#       id: current-time
#       with:
#         format: YYYYMMDD-HH.MM
#         utcOffset: "+07:00"
#     - name: Use current time
#       env:
#         F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
#       run: echo Reports $F_TIME
#     - name: Reporting
#       if: always()
#       uses: actions/upload-artifact@v2
#       with:
#         name: Reports ${{ steps.current-time.outputs.formattedTime }}
#         path: reports
