name: AutomationTesting
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: deploying
        uses: actions/checkout@v2
        run: npm install
  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: AT Run
        run: npm run test-api