name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FAKERESTAPI_BASE_URL: ${{ secrets.FAKERESTAPI_BASE_URL }}
  REQRES_BASE_URL: ${{ secrets.REQRES_BASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Module
    - uses: actions/checkout@v2
    - run: npm install
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Running Test
    - uses: actions/upload-artifact@v2
    - run: npm run test-api
  report:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Reporting
    - uses: actions/upload-artifact@v2
      name: Archive Results
      with:
        name: Reporting
        path: reports