name: Node.js CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  FAKERESTAPI_BASE_URL: ${{ secrets.FAKERESTAPI_BASE_URL }}
  REQRES_BASE_URL: ${{ secrets.REQRES_BASE_URL }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run
        run: pwd
      - name: Run
        run: ls -a
  test:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: pwd
      - name: Run
        run: ls -a